### ISSUE TITLE
black screen and crashes - grapheneos

### ISSUE THREAD

**Issue by cobordism** [c3nav/c3nav-android#38]
Hi,
I cannot see anything on c3nav android app (website works).
I am using grapheneos.

In the app, selecting 'Manage Account' closes the app.

I really cannot see what is going on, but I did manage to catch a crashlog.

```
type: crash
osVersion: google/lynx/lynx:15/AP4A.241205.013/2024121200:user/release-keys
flags: dev options enabled
package: de.c3nav.droid:14040302, targetSdk 34
process: de.c3nav.droid
processUptime: 32569 + 283 ms
installer: com.looker.droidify

java.lang.NullPointerException: uriString
	at android.net.Uri$StringUri.<init>(Uri.java:505)
	at android.net.Uri$StringUri.<init>(Unknown Source:0)
	at android.net.Uri.parse(Uri.java:467)
	at de.c3nav.droid.MainActivity$1.onNavigationItemSelected(MainActivity.java:272)
	at com.google.android.material.navigation.NavigationView$1.onMenuItemSelected(NavigationView.java:170)
	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:834)
	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:985)
	at com.google.android.material.internal.NavigationMenuPresenter$1.onClick(NavigationMenuPresenter.java:352)
	at android.view.View.performClick(View.java:8033)
	at android.view.View.performClickInternal(View.java:8010)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:31336)
	at android.os.Handler.handleCallback(Handler.java:991)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8826)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
```

**Comment by gwenya** [comment]
Are you using the latest version? If so, we’d love if you could come by our assembly some time so we can debug.

**Comment by cobordism** [comment]
Got it. Need new repo for fdroid.
https://f-droid.c3nav.de/fdroid/repo?fingerprint=C1EC2D062F67A43F87CCF95B8096630285E1B2577DC803A0826539DF6FB4C95D
